### ISSUE TITLE
编译不通过         

### ISSUE THREAD

**Issue by assqingt** [9176324/Shark#10]
1>LINK : fatal error LNK1123: failure during conversion to COFF: file invalid or corrupt
1>NMAKE : fatal error U1077: 'link.exe' : return code '0x463'

**Comment by 9176324** [comment]
![20190305143611](https://user-images.githubusercontent.com/4614528/53785607-11cd9800-3f54-11e9-9280-81f1e72f538c.png)
不存在的

**Comment by luciouskami** [comment]
不存在的+1
![build](https://user-images.githubusercontent.com/10268785/54073060-bd147f00-42bd-11e9-82a9-1e447abcb648.png)
自己找找原因为什么会失败。

**Comment by MichaelDavidGK** [comment]
This happens because u compile it on new windows 10 SDK and on newer version of VS, u should use VS 2015 and win 8.1 SDK....
Actually @9176324 should update code to newer SDK and VS
