### ISSUE TITLE
NEW 19H1 18362 BSOD

### ISSUE THREAD

**Issue by kitty8904** [9176324/Shark#11]
The new 18362 version has been confirmed

BSOD at driver startup

Will be updated in April

**Comment by 9176324** [comment]
追不上微软的步伐 无力维护

**Comment by kitty8904** [comment]
> 追不上微软的步伐 无力维护

Is there no longer a patch because of the speed of Microsoft updates?

Do you have any more updates in the future?

And some times blue screen occurs in win10 17763.437(REDSTONE5)

**Comment by 9176324** [comment]
有时间就更吧 这东西爆炸一般是特征问题

**Comment by hzqst** [comment]
> > 追不上微软的步伐 无力维护
> 
> Is there no longer a patch because of the speed of Microsoft updates?
> 
> Do you have any more updates in the future?
> 
> And some times blue screen occurs in win10 17763.437(REDSTONE5)

in 18362 pgentry code has been changed.
locate it from IDA and modify the signature of pg entry please.

**Comment by kitty8904** [comment]
<img width="903" alt="cmp" src="https://user-images.githubusercontent.com/18622105/58326487-e928b080-7e67-11e9-9b15-6fc42a769fe9.png">

19H1 ntoskrnl.CmpAppendDllSection Kernel NOT Function Data

There is no CmpAppendDllSection function

How do I create a missing function again?

19H1 has a lost function

**Comment by hzqst** [comment]
> <img alt="cmp" width="903" src="https://user-images.githubusercontent.com/18622105/58326487-e928b080-7e67-11e9-9b15-6fc42a769fe9.png">
> 
> 19H1 ntoskrnl.CmpAppendDllSection Kernel NOT Function Data
> 
> There is no CmpAppendDllSection function
> 
> How do I create a missing function again?
> 
> 19H1 has a lost function

hey man, CmpAppendDllSection is inside INIT section. How could you read code/memory from a section which is unmapped after system initialization?

**Comment by kitty8904** [comment]
So why search and use the initialization section in the source?

19H1 removed the initialization section, but previous versions of Windows still exist

//////////////////////////////////////////////////////////////

You can find the above area by looking at KernelExplorer or cheat engine pdb

**Comment by hzqst** [comment]
> So why search and use the initialization section in the source?
> 
> 19H1 removed the initialization section, but previous versions of Windows still exist
> 
> //////////////////////////////////////////////////////////////
> 
> You can find the above area by looking at KernelExplorer or cheat engine pdb

we search CmpAppendDllSection from ntoskrnl.exe PE file, not a existing /loaded ntos image.

**Comment by kitty8904** [comment]
> we search CmpAppendDllSection from ntoskrnl.exe PE file, not a existing /loaded ntos image


I have PE file search results

If so, where did pattern scan area change in 19H1?

https://github.com/9176324/Shark/blob/master/Projects/Shark/AMD64/PatchGuardAMD64.c <?

**Comment by hzqst** [comment]
> > we search CmpAppendDllSection from ntoskrnl.exe PE file, not a existing /loaded ntos image
> 
> I have PE file search results(
> 
> If so, where did pattern scan area change in 19H1?
> 
> https://github.com/9176324/Shark/blob/master/Projects/Shark/AMD64/PatchGuardAMD64.c <here?

pattern scan area never changes
I still found CmpAppendDllSection inside INIT section from manually mapped PE file with ZwMapViewOfSection, works fine for any version of Windows 10.

**Comment by kitty8904** [comment]
Thank you for your response

If it is not a pattern problem, what is the problem with the source? 19H1 produces a blue screen

**Comment by hzqst** [comment]
> Thank you for your response
> 
> If it is not a pattern problem, what is the problem with the source? 19H1 produces a blue screen

I've said before
in 18362 pgentry code has been changed.
locate it from IDA and modify the signature of pg entry please.

pg entry != CmpAppendDllSection

**Comment by kitty8904** [comment]
CmpAppendDllSection this is not a problem Ok

What is a pg entry? Where do you say it from the source? I'm sorry I did not know

I do not know where the PG entry to the source

**Comment by hzqst** [comment]
> CmpAppendDllSection this is not a problem Ok
> 
> What is a pg entry? Where do you say it from the source? I'm sorry I did not know
> 
> I do not know where the PG entry to the source

https://github.com/9176324/Shark/blob/3f7d5ffc8c09acf2b2335f6a3b6f699bf708bc2b/Projects/Shark/AMD64/PatchGuardAMD64.c#L233

**Comment by kitty8904** [comment]
//RS1-RS5
CHAR Header[] = "55 41 54 41 55 41 56 41 57 48 81 EC C0 02 00 00 48 8D A8 D8 FD FF FF 48 83 E5 80"; 

//19H1
CHAR Header[] = "55 41 54 41 55 41 56 41 57 48 8D 68 A1 48 81 EC B0 00 00 00 8B 82"; 

Thanks for your answer
