### ISSUE TITLE
sometime BSOD - SYSTEM_THREAD_EXCEPTION_NOT_HANDLED

### ISSUE THREAD

**Issue by YangKi1902** [9176324/Shark#13]
hello, sometime i got BSOD with SYSTEM_THREAD_EXCEPTION_NOT_HANDLED code, same with windows 7 and windows 10 64 bit, here the log : 

`*******************************************************************************
*                                                                             *
*                        Bugcheck Analysis                                    *
*                                                                             *
*******************************************************************************

SYSTEM_THREAD_EXCEPTION_NOT_HANDLED (7e)
This is a very common bugcheck.  Usually the exception address pinpoints
the driver/function that caused the problem.  Always note this address
as well as the link date of the driver/image that contains this address.
Arguments:
Arg1: ffffffffc000001d, The exception code that was not handled
Arg2: ffffa981810a2a54, The address that the exception occurred at
Arg3: ffff8c095bacf7a8, Exception Record Address
Arg4: ffff8c095baceff0, Context Record Address

Debugging Details:
------------------

KEY_VALUES_STRING: 1

STACKHASH_ANALYSIS: 1

TIMELINE_ANALYSIS: 1

DUMP_CLASS: 1

DUMP_QUALIFIER: 401

BUILD_VERSION_STRING:  17763.1.amd64fre.rs5_release.180914-1434

SYSTEM_MANUFACTURER:  Razer

SYSTEM_PRODUCT_NAME:  Blade Stealth

SYSTEM_SKU:  RZ09-02393E31

SYSTEM_VERSION:  4.06

BIOS_VENDOR:  Razer

BIOS_VERSION:  3.02

BIOS_DATE:  02/22/2018

BASEBOARD_MANUFACTURER:  Razer

BASEBOARD_PRODUCT:  Blade Stealth

DUMP_TYPE:  1

BUGCHECK_P1: ffffffffc000001d

BUGCHECK_P2: ffffa981810a2a54

BUGCHECK_P3: ffff8c095bacf7a8

BUGCHECK_P4: ffff8c095baceff0

EXCEPTION_CODE: (NTSTATUS) 0xc000001d - {EXCEPTION}  Illegal Instruction  An attempt was made to execute an illegal instruction.

FAULTING_IP: 
+0
ffffa981`810a2a54 c7              ???

EXCEPTION_RECORD:  ffff8c095bacf7a8 -- (.exr 0xffff8c095bacf7a8)
ExceptionAddress: ffffa981810a2a54
   ExceptionCode: c000001d (Illegal instruction)
  ExceptionFlags: 00000000
NumberParameters: 0

CONTEXT:  ffff8c095baceff0 -- (.cxr 0xffff8c095baceff0)
rax=ffffa981810bb31f rbx=ffffa981810bb31f rcx=ffffa981810a02d9
rdx=0000000000000000 rsi=ffffa981810a0a59 rdi=ffffa981810a02d9
rip=ffffa981810a2a54 rsp=ffff8c095bacf9e0 rbp=fffff801419af7d0
 r8=0000000000000023  r9=0000000000000000 r10=fffff801419af7d0
r11=0000000000000000 r12=0000000000000000 r13=0000000000000000
r14=ffffa9817ec7fc1a r15=fffff80141d72240
iopl=0         nv up ei ng nz na po nc
cs=0010  ss=0018  ds=002b  es=002b  fs=0053  gs=002b             efl=00010286
ffffa981`810a2a54 c7              ???
Resetting default scope

CPU_COUNT: 8

CPU_MHZ: 7c8

CPU_VENDOR:  GenuineIntel

CPU_FAMILY: 6

CPU_MODEL: 8e

CPU_STEPPING: a

CPU_MICROCODE: 6,8e,a,0 (F,M,S,R)  SIG: 84'00000000 (cache) 84'00000000 (init)

BLACKBOXBSD: 1 (!blackboxbsd)

BLACKBOXPNP: 1 (!blackboxpnp)

DEFAULT_BUCKET_ID:  WIN8_DRIVER_FAULT

BUGCHECK_STR:  AV

PROCESS_NAME:  System

CURRENT_IRQL:  0

ERROR_CODE: (NTSTATUS) 0xc000001d - {EXCEPTION}  Illegal Instruction  An attempt was made to execute an illegal instruction.

EXCEPTION_CODE_STR:  c000001d

ANALYSIS_SESSION_HOST:  DESKTOP-QPBMC3H

ANALYSIS_SESSION_TIME:  04-22-2019 22:26:49.0234

ANALYSIS_VERSION: 10.0.17763.132 amd64fre

LAST_CONTROL_TRANSFER:  from 000000007e7cf03d to ffffa981810a2a54

FAILED_INSTRUCTION_ADDRESS: 
+0
ffffa981`810a2a54 c7              ???

STACK_TEXT:  
ffff8c09`5bace788 fffff801`419e01b1 : 00000000`0000007e ffffffff`c000001d ffffa981`810a2a54 ffff8c09`5bacf7a8 : nt!KeBugCheckEx
ffff8c09`5bace790 fffff801`419a346f : 00000000`00000003 ffff8c09`5bacfb10 ffff8c09`5bac9000 ffff8c09`5bad0000 : nt!PspSystemThreadStartup$filt$0+0x44
ffff8c09`5bace7d0 fffff801`419d121f : ffff8c09`5bacfb10 ffff8c09`5bacedb0 ffff8c09`5bacee90 00000000`0010001f : nt!_C_specific_handler+0x9f
ffff8c09`5bace840 fffff801`4192a240 : ffff8c09`5bacee90 00000000`00000000 ffff8c09`5bacedb0 00000000`00000000 : nt!RtlpExecuteHandlerForException+0xf
ffff8c09`5bace870 fffff801`41837ac4 : ffff8c09`5bacf7a8 ffff8c09`5bacf4f0 ffff8c09`5bacf7a8 ffffa981`810a02d9 : nt!RtlDispatchException+0x430
ffff8c09`5bacefc0 fffff801`419d9f42 : 00000000`00000000 00000000`00000000 00000000`00000000 fffff801`41817e22 : nt!KiDispatchException+0x144
ffff8c09`5bacf670 fffff801`419d478e : ffffbe00`2b9d8200 00000000`00000001 ffffa981`8c5e33c0 00000000`00000000 : nt!KiExceptionDispatch+0xc2
ffff8c09`5bacf850 ffffa981`810a2a54 : 00000000`7e7cf03d ffffa981`810bb328 ffffa981`00000000 ffffa981`7eca8680 : nt!KiInvalidOpcodeFault+0x30e
ffff8c09`5bacf9e0 00000000`7e7cf03d : ffffa981`810bb328 ffffa981`00000000 ffffa981`7eca8680 ffffe78c`00000000 : 0xffffa981`810a2a54
ffff8c09`5bacf9e8 ffffa981`810bb328 : ffffa981`00000000 ffffa981`7eca8680 ffffe78c`00000000 00000000`00000000 : 0x7e7cf03d
ffff8c09`5bacf9f0 ffffa981`00000000 : ffffa981`7eca8680 ffffe78c`00000000 00000000`00000000 ffffa981`7eca8680 : 0xffffa981`810bb328
ffff8c09`5bacf9f8 ffffa981`7eca8680 : ffffe78c`00000000 00000000`00000000 ffffa981`7eca8680 fffff801`558fd50c : 0xffffa981`00000000
ffff8c09`5bacfa00 ffffe78c`00000000 : 00000000`00000000 ffffa981`7eca8680 fffff801`558fd50c ffffa981`8fe2f640 : 0xffffa981`7eca8680
ffff8c09`5bacfa08 00000000`00000000 : ffffa981`7eca8680 fffff801`558fd50c ffffa981`8fe2f640 fffff801`41d72240 : 0xffffe78c`00000000

THREAD_SHA1_HASH_MOD_FUNC:  0305f1688681aebed0adad04f2a1f9bbfa632561

THREAD_SHA1_HASH_MOD_FUNC_OFFSET:  d02f21f1f7e352aab835030d8af9e02e0e8a177a

THREAD_SHA1_HASH_MOD:  cb5f414824c2521bcc505eaa03e92fa10922dad8

FOLLOWUP_IP: 
nt!PspSystemThreadStartup$filt$0+44
fffff801`419e01b1 90              nop

FAULT_INSTR_CODE:  c4834890

SYMBOL_STACK_INDEX:  1

SYMBOL_NAME:  nt!PspSystemThreadStartup$filt$0+44

FOLLOWUP_NAME:  MachineOwner

MODULE_NAME: nt

IMAGE_NAME:  ntkrnlmp.exe

DEBUG_FLR_IMAGE_TIMESTAMP:  438ffec3

STACK_COMMAND:  .thread ; .cxr ; kb

BUCKET_ID_FUNC_OFFSET:  44

FAILURE_BUCKET_ID:  AV_BAD_IP_nt!PspSystemThreadStartup$filt$0

BUCKET_ID:  AV_BAD_IP_nt!PspSystemThreadStartup$filt$0

PRIMARY_PROBLEM_CLASS:  AV_BAD_IP_nt!PspSystemThreadStartup$filt$0

TARGET_TIME:  2019-04-22T15:08:01.000Z

OSBUILD:  17763

OSSERVICEPACK:  0

SERVICEPACK_NUMBER: 0

OS_REVISION: 0

SUITE_MASK:  784

PRODUCT_TYPE:  1

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

OSEDITION:  Windows 10 WinNt TerminalServer SingleUserTS Personal

OS_LOCALE:  

USER_LCID:  0

OSBUILD_TIMESTAMP:  2005-12-02 14:58:59

BUILDDATESTAMP_STR:  180914-1434

BUILDLAB_STR:  rs5_release

BUILDOSVER_STR:  10.0.17763.1.amd64fre.rs5_release.180914-1434

ANALYSIS_SESSION_ELAPSED_TIME:  4e6

ANALYSIS_SOURCE:  KM

FAILURE_ID_HASH_STRING:  km:av_bad_ip_nt!pspsystemthreadstartup$filt$0

FAILURE_ID_HASH:  {32e528d8-24a5-3b2e-58ad-3857d4ab6660}

Followup:     MachineOwner
---------`

**Comment by 9176324** [comment]
应该是 重新启动 ExpWorkerThread 的时候 环境出了问题 可以选择直接干掉线程

**Comment by InvisK** [comment]
hello, can you tech me a snippet for it ?

**Comment by hzqst** [comment]
> hello, can you tech me a snippet for it ?

should be fixed now.

**Comment by InvisK** [comment]
> > hello, can you tech me a snippet for it ?
> 
> should be fixed now.

thanks, i will try to test.

**Comment by d0r4emon** [comment]
请教这个bug是如何解决的？我用了如下补丁，问题依旧。

```
#define __ROL64(x, n) (((x) << ((( n & 0xFF) % 64))) | ((x) >> (64 - (( n & 0xFF) % 64))))
#define __ROR64(x, n) (((x) >> ((( n & 0xFF) % 64))) | ((x) << (64 - (( n & 0xFF) % 64))))
=>
#define __ROL64(x, n) (((x) << ((n) & 0x3F)) | ((x) >> (64 - ((n) & 0x3F))))
#define __ROR64(x, n) (((x) >> ((n) & 0x3F)) | ((x) << (64 - ((n) & 0x3F))))

<minidump>
3: kd> k
 # Child-SP          RetAddr           Call Site
00 ffff808e`46246fe8 fffff806`4d41128d nt!KeBugCheckEx
01 ffff808e`46246ff0 fffff806`4d3dfe42 nt!KiDispatchException+0x18a55d
02 ffff808e`462476a0 fffff806`4d3da68e nt!KiExceptionDispatch+0xc2
03 ffff808e`46247880 ffffb00e`aed7286b nt!KiInvalidOpcodeFault+0x30e
04 ffff808e`46247a10 ffffffff`bd3bf7cd 0xffffb00e`aed7286b
05 ffff808e`46247a18 ffffb00e`aed8b13f 0xffffffff`bd3bf7cd
06 ffff808e`46247a20 ffffb00e`b77ca080 0xffffb00e`aed8b13f
07 ffff808e`46247a28 fffff806`4d778240 0xffffb00e`b77ca080
08 ffff808e`46247a30 00000000`00000000 nt!ExNode0

<disassemble ffffb00e`aed72860>
ffffb00e`aed72860 cc              int     3
ffffb00e`aed72861 cc              int     3
ffffb00e`aed72862 cc              int     3
ffffb00e`aed72863 cc              int     3
ffffb00e`aed72864 cc              int     3
ffffb00e`aed72865 cc              int     3
ffffb00e`aed72866 68cdf73bbd      push    0FFFFFFFFBD3BF7CDh
ffffb00e`aed7286b c7              ???
ffffb00e`aed7286c 5c              pop     rsp
ffffb00e`aed7286d 2404            and     al,4
ffffb00e`aed7286f 0e              ???
ffffb00e`aed72870 b0ff            mov     al,0FFh
ffffb00e`aed72872 ffc3            inc     ebx
ffffb00e`aed72874 204889          and     byte ptr [rax-77h],cl
ffffb00e`aed72877 48085541        or      byte ptr [rbp+41h],dl
ffffb00e`aed7287b 54              push    rsp
```
