### ISSUE TITLE
Win10 1809 (17763.529) 解密后重新加密写入 PG执行解密会有几率错误

### ISSUE THREAD

**Issue by wbaby** [9176324/Shark#14]
正常解密后执行应该为
ffffbc87`a61047d3 68cde35aad         push    0FFFFFFFFAD5AE3CDh

ffffbc87`a61047d8 c744240487bcffff   mov     dword ptr [rsp+4], 0FFFFBC87h

ffffbc87`a61047e0 c3                 ret     

但是触发BugCheck后看到Dump执行代码为
ffffbc87`a61047d3 68cde35aad     push    0FFFFFFFFAD5AE3CDh

ffffbc87`a61047d8 c7             ???     

ffffbc87`a61047d9 5c             pop     rsp

ffffbc87`a61047da 2404           and     al, 4

ffffbc87`a61047dc 87bcffffc32048 xchg    edi, dword ptr [rdi+rdi*8+4820C3FFh]

ffffbc87`a61047e3 894808         mov     dword ptr [rax+8], ecx

ffffbc87`a61047e6 55             push    rbp

ffffbc87`a61047e7 4154           push    r12

ffffbc87`a61047e9 4155           push    r13

ffffbc87`a61047eb 4156           push    r14

ffffbc87`a61047ed 4157           push    r15

解出的代码不对 44被解成5C

**Comment by wbaby** [comment]
[052719-11765-01.zip](https://github.com/9176324/Shark/files/3224428/052719-11765-01.zip)

Dump文件

**Comment by wbaby** [comment]
Rorkey 有几率解错,已经解决,很不错的项目

**Comment by 9176324** [comment]
暂时找不到原因 在PgSetNewEntry 和 PgSetNewEntryWithBtc 中的DetourLockedBuildJumpCode 处设置__debugbreak() 看下建立的Jump 代码 是不是有问题 目前没有环境 无法测试

**Comment by wbaby** [comment]
可以确定是PgSetNewEntryWithBtc中 看了 确定DetourLockedBuildJumpCode设置的代码是没问题的

**Comment by wbaby** [comment]
Win10 1809 (17763.529) 是目前17763.x 最新的补丁

**Comment by hzqst** [comment]
#13 probably the same problem.

**Comment by 9176324** [comment]
应该可以了

**Comment by wbaby** [comment]
> 应该可以了

您好,作者,感谢您的回复
忘记回复了,已经解决,RorKey解的有问题

**Comment by wbaby** [comment]
> #13 probably the same problem.
> 如果DetourLockedBuildJumpCode打断点发现代码当时是OK的，那么就是加密回去的时候姿势不对
> @wbaby 建议给DetourLockedBuildJumpCode之前打断点看copy进来的代码是不是正确的

您好,hzqst,我认为是一个问题

**Comment by d0r4emon** [comment]
> > 应该可以了
> 
> 您好,作者,感谢您的回复
> 忘记回复了,已经解决,RorKey解的有问题,有多组解的可能

请教这个bug是如何解决的？我用了如下补丁，问题依旧。
#define __ROL64(x, n) (((x) << ((( n & 0xFF) % 64))) | ((x) >> (64 - (( n & 0xFF) % 64))))
#define __ROR64(x, n) (((x) >> ((( n & 0xFF) % 64))) | ((x) << (64 - (( n & 0xFF) % 64))))
=>
#define __ROL64(x, n) (((x) << ((n) & 0x3F)) | ((x) >> (64 - ((n) & 0x3F))))
#define __ROR64(x, n) (((x) >> ((n) & 0x3F)) | ((x) << (64 - ((n) & 0x3F))))

<minidump>
3: kd> k
 # Child-SP          RetAddr           Call Site
00 ffff808e`46246fe8 fffff806`4d41128d nt!KeBugCheckEx
01 ffff808e`46246ff0 fffff806`4d3dfe42 nt!KiDispatchException+0x18a55d
02 ffff808e`462476a0 fffff806`4d3da68e nt!KiExceptionDispatch+0xc2
03 ffff808e`46247880 ffffb00e`aed7286b nt!KiInvalidOpcodeFault+0x30e
04 ffff808e`46247a10 ffffffff`bd3bf7cd 0xffffb00e`aed7286b
05 ffff808e`46247a18 ffffb00e`aed8b13f 0xffffffff`bd3bf7cd
06 ffff808e`46247a20 ffffb00e`b77ca080 0xffffb00e`aed8b13f
07 ffff808e`46247a28 fffff806`4d778240 0xffffb00e`b77ca080
08 ffff808e`46247a30 00000000`00000000 nt!ExNode0

<disassemble ffffb00e`aed72860>
ffffb00e`aed72860 cc              int     3
ffffb00e`aed72861 cc              int     3
ffffb00e`aed72862 cc              int     3
ffffb00e`aed72863 cc              int     3
ffffb00e`aed72864 cc              int     3
ffffb00e`aed72865 cc              int     3
ffffb00e`aed72866 68cdf73bbd      push    0FFFFFFFFBD3BF7CDh
ffffb00e`aed7286b c7              ???
ffffb00e`aed7286c 5c              pop     rsp
ffffb00e`aed7286d 2404            and     al,4
ffffb00e`aed7286f 0e              ???
ffffb00e`aed72870 b0ff            mov     al,0FFh
ffffb00e`aed72872 ffc3            inc     ebx
ffffb00e`aed72874 204889          and     byte ptr [rax-77h],cl
ffffb00e`aed72877 48085541        or      byte ptr [rbp+41h],dl
ffffb00e`aed7287b 54              push    rsp
