### ISSUE TITLE
Sometimes,PrintSymbol shows wrong name

### ISSUE THREAD

**Issue by wbaby** [9176324/Shark#15]
https://github.com/9176324/Shark/blob/db4b6b6fa107dbea6acf03a98f335addccf1c4db/Projects/Shark/Stack.c#L156

fix:
Symbol->String =  (PCHAR)Symbol->DataTableEntry->DllBase + NameTable[NameIndex];

**Comment by InvisK** [comment]
it's not so matter, just a breakline mistake.
`                            Symbol->String = //already assigned
                                (PCHAR)Symbol->DataTableEntry->DllBase + NameTable[HintIndex];`

**Comment by wbaby** [comment]
> it's not so matter, just a breakline mistake, my ide is ok with it.
> 
> > Symbol->String = //already assigned
> > (PCHAR)Symbol->DataTableEntry->DllBase + NameTable[HintIndex];

not breakline mistake,and breakline is not a mistake.

Symbol->String = (PCHAR)Symbol->DataTableEntry->DllBase + NameTable[**HintIndex**];
Symbol->String = (PCHAR)Symbol->DataTableEntry->DllBase + NameTable[**NameIndex**];

**Comment by InvisK** [comment]
oh sorry, my mistake :D.

**Comment by 9176324** [comment]
这个是打印最靠近的导出表位置, 主要目的是为了定位, 而不是真的打印符号.

**Comment by wbaby** [comment]
> 这个是打印最靠近的导出表位置, 主要目的是为了定位, 而不是真的打印符号.

yes, I know what you are saying, sometimes print wrong near function name
This is my fix 
Symbol->String = (PCHAR)Symbol->DataTableEntry->DllBase + NameTable[HintIndex];
↓
Symbol->String = (PCHAR)Symbol->DataTableEntry->DllBase + NameTable[NameIndex];

works fine, now
