### ISSUE TITLE
Instantly closes

### ISSUE THREAD

**Issue by MichaelDavidGK** [9176324/Shark#17]
File just instantly closes

**Comment by 9176324** [comment]
在 debugview 中显示

**Comment by MichaelDavidGK** [comment]
'Sea.exe' (Win32): Loaded 'A:\Users\MichaelGK\Source\Repos\Shark\Build\Bins\AMD64\Sea.exe'. Symbols loaded.
'Sea.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. 
'Sea.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. 
'Sea.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. 
[Shark] Sysload.c[243] LoadKernelImage failed < c0000061 >
The program '[5044] Sea.exe' has exited with code 0 (0x0).


Sorry for late response

**Comment by 9176324** [comment]
no sign

**Comment by mrexodia** [comment]
0xC0000061 STATUS_PRIVILEGE_NOT_HELD

Run `Sea.exe` as admin
