### ISSUE TITLE
怎么编译驱动啊

### ISSUE THREAD

**Issue by qq909090376** [9176324/Shark#2]
大佬怎么编译啊 我用的VS2017

**Comment by 9176324** [comment]
@qq909090376  打开Shark 目录的 SLN 文件 即可编译  存放的目录中不要有空格

**Comment by 751620780** [comment]
It cannot be compiled in vs2017, nor can it be compiled through run build.cmd file. I don't know what specific libraries need to be installed to compile this source code.
