### ISSUE TITLE
Tutorial step-by-step !

### ISSUE THREAD

**Issue by Whibelf2** [9176324/Shark#20]
Any chance to take a step-by-step tutorial how to disable PG using you tool ?

**Comment by 9176324** [comment]
run......

**Comment by Whibelf2** [comment]
Run with administrator privilege here, test mode enabled, but no success, Version 1809 Build 17763.593

After 3 or 4 hours i get BSOD

If i make donation you create for me a tutorial how to disable PG ?

**Comment by Whibelf2** [comment]
This tool have any dependence with windows services ?

Thanks !

**Comment by Whibelf2** [comment]
Still get BSOD on new version of Tool :(
