### ISSUE TITLE
help, still BSOD somtimes, about 1/5

### ISSUE THREAD

**Issue by d0r4emon** [9176324/Shark#21]
How to solve this bug? I used the following patch and the problem is still there.

```
#define __ROL64(x, n) (((x) << ((( n & 0xFF) % 64))) | ((x) >> (64 - (( n & 0xFF) % 64))))
#define __ROR64(x, n) (((x) >> ((( n & 0xFF) % 64))) | ((x) << (64 - (( n & 0xFF) % 64))))
=>
#define __ROL64(x, n) (((x) << ((n) & 0x3F)) | ((x) >> (64 - ((n) & 0x3F))))
#define __ROR64(x, n) (((x) >> ((n) & 0x3F)) | ((x) << (64 - ((n) & 0x3F))))

<minidump>
3: kd> k
 # Child-SP          RetAddr           Call Site
00 ffff808e`46246fe8 fffff806`4d41128d nt!KeBugCheckEx
01 ffff808e`46246ff0 fffff806`4d3dfe42 nt!KiDispatchException+0x18a55d
02 ffff808e`462476a0 fffff806`4d3da68e nt!KiExceptionDispatch+0xc2
03 ffff808e`46247880 ffffb00e`aed7286b nt!KiInvalidOpcodeFault+0x30e
04 ffff808e`46247a10 ffffffff`bd3bf7cd 0xffffb00e`aed7286b
05 ffff808e`46247a18 ffffb00e`aed8b13f 0xffffffff`bd3bf7cd
06 ffff808e`46247a20 ffffb00e`b77ca080 0xffffb00e`aed8b13f
07 ffff808e`46247a28 fffff806`4d778240 0xffffb00e`b77ca080
08 ffff808e`46247a30 00000000`00000000 nt!ExNode0

<disassemble ffffb00e`aed72860>
ffffb00e`aed72860 cc              int     3
ffffb00e`aed72861 cc              int     3
ffffb00e`aed72862 cc              int     3
ffffb00e`aed72863 cc              int     3
ffffb00e`aed72864 cc              int     3
ffffb00e`aed72865 cc              int     3
ffffb00e`aed72866 68cdf73bbd      push    0FFFFFFFFBD3BF7CDh
ffffb00e`aed7286b c7              ???
ffffb00e`aed7286c 5c              pop     rsp
ffffb00e`aed7286d 2404            and     al,4
ffffb00e`aed7286f 0e              ???
ffffb00e`aed72870 b0ff            mov     al,0FFh
ffffb00e`aed72872 ffc3            inc     ebx
ffffb00e`aed72874 204889          and     byte ptr [rax-77h],cl
ffffb00e`aed72877 48085541        or      byte ptr [rbp+41h],dl
ffffb00e`aed7287b 54              push    rsp
```

**Comment by Whibelf2** [comment]
Same here

**Comment by 9176324** [comment]
![image](https://user-images.githubusercontent.com/4614528/62022162-7cca8480-b1fd-11e9-964c-e04b87dd37ef.png)
尝试在这这里断点 看看是否写入正确

**Comment by 9176324** [comment]
#ifndef _WIN64
#define SetCounterBody(body, address) \
            *(PLONG)(body)->Address = *(PLONG)&(address), \
            *(PLONG)(body)->Push[0] = 0x68

#define GetCounterBody(body, address) \
           *(PLONG)(address) = *(PLONG)(body)->Address
#else
#define SetCounterBody(body, address) \
            *(PLONG)(body)->Address = *(PLONG)&(address), \
            *(PLONG)(body)->AddressExtend = *((PLONG)&(address) + 1), \
            *(PLONG)(body)->Move[0] = 0xc7, \
            *(PLONG)(body)->Move[1] = 0x44, \
            *(PLONG)(body)->Move[2] = 0x24, \
            *(PLONG)(body)->Move[3] = 0x04, \
            *(PLONG)(body)->Push[0] = 0x68

#define GetCounterBody(body, address) \
           *(PLONG)(address) = *(PLONG)(body)->Address, \
           *((PLONG)(address) + 1) = *(PLONG)(body)->AddressExtend
#endif // !_WIN64

**Comment by 9176324** [comment]
#ifndef _WIN64
#define SetCounterBody(body, address) \
            *(PLONG)(body)->Address = *(PLONG)&(address), \
            (body)->Push[0] = 0x68

#define GetCounterBody(body, address) \
           *(PLONG)(address) = *(PLONG)(body)->Address
#else
#define SetCounterBody(body, address) \
            *(PLONG)(body)->Address = *(PLONG)&(address), \
            *(PLONG)(body)->AddressExtend = *((PLONG)&(address) + 1), \
            (body)->Move[0] = 0xc7, \
            (body)->Move[1] = 0x44, \
            (body)->Move[2] = 0x24, \
            (body)->Move[3] = 0x04, \
            (body)->Push[0] = 0x68

#define GetCounterBody(body, address) \
           *(PLONG)(address) = *(PLONG)(body)->Address, \
           *((PLONG)(address) + 1) = *(PLONG)(body)->AddressExtend
#endif // !_WIN64

**Comment by d0r4emon** [comment]
Thanks for your reply, the data is correct when writing, I use dbgprint () to print the data to be written, as expected. A very strange problem, it seems that the decryption encountered an error, or the encryption algorithm sometimes differs.

**Comment by 9176324** [comment]
your system version

**Comment by d0r4emon** [comment]
thanks, windows10, 17763.379

> your system version

**Comment by 9176324** [comment]
I will try debug it tomorrow.

**Comment by d0r4emon** [comment]
Pay tribute to your rigorous attitude towards technical research, thx.

> I will try debug it tomorrow.

**Comment by 9176324** [comment]
没调出来你说的情况, 你用的新版本?

**Comment by d0r4emon** [comment]
I repeatedly restarted 10 times in another 17763.615, which can be reproduced. It is best to wait for a while after rebooting, do not run the driver immediately.

**Comment by 9176324** [comment]
使用最新版本(2019-08-03)尝试, 我调了10次左右 没遇到.

**Comment by d0r4emon** [comment]
Maybe my have a bad luck, :P
thank you very much for your reply.

> 使用最新版本(2019-08-03)尝试, 我调了10次左右 没遇到.
