### ISSUE TITLE
win10 10.0.17134.915 bsod 

### ISSUE THREAD

**Issue by fake-cheater** [9176324/Shark#25]
dump file:
[101119-15015-01.zip](https://github.com/9176324/Shark/files/3715552/101119-15015-01.zip)

**Comment by 9176324** [comment]
用源码重新编译,不要使用二进制文件,然后自行调试.

**Comment by appleman1232** [comment]
Recompile with source code, don't use binary files, and ""debug yourself"".

For fucks sake, debug it.

**Comment by InvisK** [comment]
i have same problem, did you fixed it @myckx  ?
