### ISSUE TITLE
Open Communication port failure

### ISSUE THREAD

**Issue by Berahthraben** [9176324/Shark#26]
Not sure what's going wrong. Error code c0000034.
Running W10 build 17763.805, driver signature is off.
![image](https://user-images.githubusercontent.com/23364436/66928815-5b14b880-f008-11e9-9c37-f2349cbf565b.png)

**Comment by 9176324** [comment]
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55?redirectedfrom=MSDN

**Comment by 9176324** [comment]
自己签名
