### ISSUE TITLE
可以上传最新版本的release吗?

### ISSUE THREAD

**Issue by NewHand007** [9176324/Shark#27]
我用的VS2017,不会编译你的文件,可以可以上传支持1903最新版本的release吗?

**Comment by 9176324** [comment]
md X:\Labs
cd /d X:\Labs
git clone https://github.com/9176324/Shark
git clone https://github.com/9176324/WinDDK
git clone https://github.com/9176324/WRK


run X:\Labs\Shark\Build.cmd
