### ISSUE TITLE
vs2017 编译错误

### ISSUE THREAD

**Issue by taodaqiao** [9176324/Shark#30]
1>   Creating library D:\PGPG\Shark\Build\Bins\AMD64\Shark.lib and object D:\PGPG\Shark\Build\Bins\AMD64\Shark.exp
1>LINK : fatal error LNK1123: failure during conversion to COFF: file invalid or corrupt
1>NMAKE : fatal error U1077: 'link.exe' : return code '0x463'

**Comment by 9176324** [comment]
use build.cmd
