### ISSUE TITLE
win7-7601没有搜索到 encrypted context

### ISSUE THREAD

**Issue by GameNanny** [9176324/Shark#34]
found encrypted context 字样的打印没有出现,似乎是没有搜索到,系统版本 win7-7601
dbgview打印:

[Shark] load
[Shark] [PatchGuard] < 0000000000001DB1 > BuildNumber
[Shark] [PatchGuard] < FFFFFA8003CFE040 > PsInitialSystemProcess
[Shark] [PatchGuard] < 0000000000000001 > NumberProcessors
[Shark] [PatchGuard] < FFFFF80003EEA3D0 > KeEnterCriticalRegion
[Shark] [PatchGuard] < FFFFF80003EECDC0 > KeLeaveCriticalRegion
[Shark] [PatchGuard] < FFFFF80003E7048C > ExAcquireSpinLockShared
[Shark] [PatchGuard] < FFFFF80003E7052C > ExReleaseSpinLockShared
[Shark] [PatchGuard] < FFFFF80003F8FCD0 > DbgPrint
[Shark] [PatchGuard] < FFFFF80003EE2610 > RtlCompareMemory
[Shark] [PatchGuard] < FFFFF80003EE0E00 > RtlRestoreContext
[Shark] [PatchGuard] < FFFFF80003EECC10 > ExQueueWorkItem
[Shark] [PatchGuard] < FFFFF8000400BD90 > ExFreePoolWithTag
[Shark] [PatchGuard] < FFFFF80003EE0640 > KeBugCheckEx
[Shark] [PatchGuard] < FFFFF80003ED88D0 > ExInterlockedRemoveHeadList
[Shark] [PatchGuard] < FFFFF80003EFFBF4 > ExAcquireRundownProtection
[Shark] [PatchGuard] < FFFFF80003EFFC14 > ExReleaseRundownProtection
[Shark] [PatchGuard] < FFFFF80003EBB750 > ExWaitForRundownProtectionRelease
[Shark] [PatchGuard] < FFFFFA8003D55560 > PgBlock
[Shark] [PatchGuard] < 00000000000000C0 > SizeCmpAppendDllSection
[Shark] [PatchGuard] < 0000000000000288 > OffsetEntryPoint
[Shark] [PatchGuard] < 0000000000003A00 > SizeINITKDBG
[Shark] [PatchGuard] < FFFFFA8003E30000 > INITKDBG
[Shark] [PatchGuard] < FFFFF80003ED22C0 > ntoskrnl.exe!ExfAcquirePushLockExclusive
[Shark] [PatchGuard] < FFFFF80003E705B0 > ntoskrnl.exe!ExfReleasePushLockExclusive
[Shark] [PatchGuard] < FFFFF80003EEA730 > ntoskrnl.exe!KeAcquireInStackQueuedSpinLockAtDpcLevel
[Shark] [PatchGuard] < FFFFF80003E7048C > ntoskrnl.exe!ExAcquireSpinLockShared
[Shark] [PatchGuard] < FFFFF8000404F470 > PsInvertedFunctionTable
[Shark] [PatchGuard] < FFFFF80003ED1FD0 > KiStartSystemThread
[Shark] [PatchGuard] < FFFFF8000417DC74 > PspSystemThreadStartup
[Shark] [PatchGuard] < FFFFF80003F72AD0 > MmIsNonPagedSystemAddressValid
[Shark] [PatchGuard] < FFFFF8000407E217 > PoolBigPageTable
[Shark] [PatchGuard] < FFFFF8000407E210 > PoolBigPageTableSize
[Shark] [PatchGuard] < 000000000002D000 > NumberOfPtes
[Shark] [PatchGuard] < FFFFF6FC40000000 > BasePte
[Shark] [PatchGuard] < FFFFF80003F0B1C0 > RtlLookupFunctionEntry
[Shark] [PatchGuard] < FFFFF80003E70C5C > RtlVirtualUnwind
[Shark] [PatchGuard] < FFFFF80003EECC10 > ExQueueWorkItem
[Shark] [PatchGuard] < FFFFFA8003D556B0 > CaptureContext
[Shark] [PatchGuard] < FFFFFA8003D55930 > FreeWorker
[Shark] [PatchGuard] < FFFFFA8003D559E0 > ClearCallback
[Shark] [PatchGuard] < 0000000000000000 > BigPool < FFFA8004C9000000 - 00008000 >
[Shark] - unload

以前的版本能正常搜索到,但是偶尔蓝屏,似乎也是 PgCompareFields函数里蓝的

**Comment by 9176324** [comment]
回头我看下 现在没有环境

**Comment by 9176324** [comment]
已修复

**Comment by GameNanny** [comment]
非常感谢作者的回复和修复,谢谢!
