### ISSUE TITLE
tried running build.cmd but there is an error

### ISSUE THREAD

**Issue by RandomArthur234** [9176324/Shark#35]
i type in build.cmd in prompt but its given `'NMAKE' is not recognized as an internal or external command,
operable program or batch file.`, tried to use the nmake.exe from the wdk repo nothing happend. tried it with vs next but no luck I get an error message, still something about Nmake.... help

**Comment by 9176324** [comment]
md X:\Labs
cd /d X:\Labs
git clone https://github.com/9176324/Shark
git clone https://github.com/9176324/WinDDK
git clone https://github.com/9176324/WRK
