### ISSUE TITLE
109 there are many. I hope you can give me some advice

### ISSUE THREAD

**Issue by 884745744** [9176324/Shark#37]
109 there are many. I hope you can give me some advice

[dump.zip](https://github.com/9176324/Shark/files/7099644/dump.zip)

**Comment by 884745744** [comment]
I am Chinese, the system is Chinese, and the system of friends around me is also easy to 109 collapse

**Comment by hzqst** [comment]
![40IDL2W08%TMWX2{7NI980N](https://user-images.githubusercontent.com/12287588/132116262-ad3d4799-b2fe-4e0e-926d-a7c91b7ce402.png)
