### ISSUE TITLE
WIN10 17134 PassPG失败

### ISSUE THREAD

**Issue by number201724** [9176324/Shark#6]
目前确认到的是可以成功Pass一部分，但是有一些长时间的PG没有PASS掉 大概会在6个小时以后得到 BugCheck 109

[minidump](https://1drv.ms/u/s!ApzUUl0e70xCnXChBrklCrLbhmy1)

**Comment by killvxk** [comment]
因为16299以后的win10的PG有个CALLBACK不走寻常路。

**Comment by number201724** [comment]
_guard_icall 这个吗？
